apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: advise-reporter
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/thoth-station/advise-reporter:v0.7.3
    importPolicy: {}
    referencePolicy:
      type: Local
