---
kind: ConfigMap
apiVersion: v1
metadata:
  name: slo-reporter
data:
  thanos-endpoint: "http://prometheus-portal-thoth-infra-prod.apps.cnv.massopen.cloud"   # TODO: Use Thanos endpoint when available and set correct secret
  smtp-server: "smtp.sendgrid.net"
  sender-address: "slo-reporter@thoth-station.ninja"
  email-recipients: "aicoe@redhat.com"
