apiVersion: v1
items:
-   apiVersion: v1
    data:
        token: ""
        sendgrid-api-key: ENC[AES256_GCM,data:Mi0FhvnXKMYm3NOlr97Teo1lm6e+oQBtMyKPYMfC/wnXVJWCiLXc3h/b1qNWjVcA3GS713mBtB+XhaOKcxI/YIcl4kPVscwdTGvN0q+E/4xesfbjxAOtsxDwVSg=,iv:nxxhdLmPtDXXWuV85V1EZhFLS9ArnRvQdbg8Y9uxAIg=,tag:bqtZ1QQrmVbxgJHclGUdwA==,type:str]
    kind: Secret
    metadata:
        name: slo-reporter
    type: Opaque
kind: List
metadata:
    resourceVersion: ""
    selfLink: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-02-08T15:26:12Z'
    mac: ENC[AES256_GCM,data:OcAUxYcIMSjOpCtGQPuyFeeanHC91cL35UYDAd8kxRhE4+LJ0lqbRyFFZBySCVa9hjCtuOHikNoQ0I+sXdeLAsCQvGpVwhq5tHg/ixmeAtZBxdgxtsrNk+sq/Bnzf/xv6bXxHPPpYT3p7oCP9hPtBLTSXMKPzK1hkI53cV6XCTk=,iv:8qlG/EwvcI+53I6X6/bBQiostKyfsxdX6WeCkZSyE2o=,tag:q0xDiy4cCogt78iEo2WuCQ==,type:str]
    pgp:
    -   created_at: '2021-02-08T15:26:11Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1gbAjViyxWYARAAf2lqgAz0fG+JTGsciVmFjFm1gol5Wpy327vB4jlvLQaM
            tHU40Pbrxz8WLUlTPmjX9TqLQ3ViUbjlgRVuHFIBoY4CUR3H0TYnph+WjnElFUmS
            mhjOxkAgTySbRJGGjfxN7kZlnR4O+h3BuNzvKBWX9XtxQtR72Xv7yO/Rk3RQqtYh
            IUbs7rZ/e5Bqrq0mAp226hAXdnyDerLpzN1G1mqZV7VOB0ijS/qXAtcgy45bMYyu
            UrKC8xUGhaYariQjbEL9745PDgQ/vrgdlOnsQdboQ+WIRrkj4AVP/fWDyi6DnRvD
            ojvBo1c9VrNM2c6gdPqz+LNaWW0JNKb2bMi4uX/Lg3fFQvh8Jw7GzHo09eVdXnfZ
            EdSejJaD4Xk6cIA5Q18YR2CKxa+6iK8ayivD8VVb0TrC7SU1/9Jt7jpCgMLtJaxM
            w3qK9mUzI2uCmj//iyhWADkywWV/pdjeJ09shSpXRwH3rWFWy1rLS3A/VcAehSjh
            tYBw7uHXGaFPGK7uL8MOKWjXbNyZ4bxr5v8aNbSKmc6C3KpvK7v3WR9LBfXW9L82
            uVb0tnGDf7XR5iS2NMZHzvGkZZL4nNX6iqRB+xWmzWp6bAd+oqrN2ZyD8n7ar3LF
            TLaWpW1QuItNAIMwL2yvUazyc4AvTIeYU+yuafx65Kky7KZtbl2B5wq9d5wDadDS
            4AHk9EgxeA80LKMSTxt1JUfS0eEf1uBY4Kjh/RbgvuK1mpQF4EXlq6f1bMUwWGBw
            F5eE/1Uek2pZ/TorEXlw3CO1P8shIvbgnuRiK5/mNI+EDOp1vVhrW9YS4j0KQurh
            UtUA
            =eWAN
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-02-08T15:26:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf+P9iaAl1pEidmgW1UYPELHJfVyjv4FXTPrjggVGJOQhWZ
            DiaWcWtpnds8XOvOEna6NkMkqzPxnOEJXsdD2qgOJjr0vjU/UuU7LwTFkO/pDqgN
            I1EAhnWZI6ROP10tR4Iscx2xvFyFjTcjKkTkt2VBGB2sbsvxUaqLsVvTPvniATFK
            9w80eOS7vtjz4U8192GDoyYD517guY7OU4rreU4juA6EYq8b6o/4ReyfAPLVgLUp
            WEqi4x1aQwPjzt+WwPA3gelbjoiILLBBJtG6jUkQ7yMLepAnc4mU3YPrB1PzDZrr
            wApbtXkwJFBEFpTghrqXRe0x+xMOM+UeNx5g1CeGq9JeAdxge+OugI6DbcTLQV12
            iSVLNMGl5V/0V2dztKmyM85xpDqf276AvMhQ1ySpUUIVzoh/GxjrDxKUmsT9mced
            FEXWIAzDpfMGTzqIpGb/XWn+AN/b48MDEyWu2qiZ+A==
            =QwQQ
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-02-08T15:26:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/cP8N3xv/0909F/gD5H1ONFxk/aVxlrgXduyjb+zCWFE8
            u/ZwYVSXNptboQHD3T3tevjsmTuXbRm4Y4Cx9YRQ9ZlzKoEyFfPd9SRMDQEJWKpD
            sWV47SPvVJNKz5KYLYQqv7oVKDG86NroXif/Jd1Q+MVYNpRCra6X8iR/DrS8CH65
            bSUItySUfTNUrGAvFgoyN9xAtd3jqW8Atx60cvdXJ+wpdlfeyaW+QiLVZyfCnBs0
            GxxQNnndZFRMLfcE1whwLJjv9XMlIO1p/1nJroebKMqCecugLXB8Cf+dqIZNhSbz
            m9r5buqrnprkNZbUtB7OCGSWng+znm0IS+91xImFONJeAc2p3AswS9AnMUeihEhX
            t2Esaqpdt7BmcttryDVAk7Gtw5riIIwK0QLOC28iTTohQBD+0zyu1X+mKzo/E2H7
            qp9CzR69KUUAbqPqihytrLZ0F/m2zuH72fmj+rnRaQ==
            =mTEK
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-02-08T15:26:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7vMDF1jUn3mAQ//XFrayfDsKU5kWOBkMVOfGIkfbK1zjWsp4KqxCOrUwUK4
            RgbwizXMPdKsNiOlnJsHbD99bVe5sD6Ts0FpgWNk7UgvYkRCD7gM29RovbRyTFnE
            +3NXRWVAtC0popZq8+i57XR38l/ZxuN/bYbNTsDvCnsZ/jBb74qF4e930IGbDfhm
            J2XnsxIHsD1h5/gfpXhFfyu/QuTm4HbpFF6cRX2PlH6ZatGKL3D36gXVFiT37AWA
            1yMDuXJ5fFqpfLsduig7dCbYNk9/7SLBV6ex/N+w5fMe/fl/vZhZZOAFfss119qk
            /UJuiNij10U08ED1RUtz6U4xEwpLW0gDL4oPYsBAOE/6KJZMOxKJ2geZ2DcgamoJ
            1vDj23pA2aCu5IjJ8KugydbIzLiVddx4Rzfi9ZtUm+mrbqLzrXqL6w13K3CvZeFV
            RI3y8JVfysHvql10L4nuLNPHU+Qblya6vVT2cql/Cr9ZgDwOdVDUPud+Uni3XggC
            h5Ucddd9Rq3udaarXkYeA2HZv8ZdycDkobBmzPjopDpQrYtjbO7hivcoWqNSFc2/
            o2LELGQFOZBI+NzaQ+QMcUYdS/o/qR/Cnl6uuHGDnQeD+aixosBdlPQumKwtQv9w
            Azlj1W/kouEgK7373qKe5PpCUNfIAbO3/8ZVNJ/R6evMbpBw2UBTWgTEWtc4j5HS
            XgHZcBjIDFS7NULMU2TXWBSZ0bba6aaw/zLOrAjVnmWyW91JYXzNxC3WplDDlqKF
            DOrxfAYBssxggpSPVbKxvVMgEgMN4pSl0IKtzK3ygHOQHwNlgWj7L+Axkh5drPU=
            =dVUY
            -----END PGP MESSAGE-----
        fp: 68BD1529A372C8BA561C9DDC377298152D08B95B
    -   created_at: '2021-02-08T15:26:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiARAAxIuaUKl5GnCl7+G6yv8WEUSCmLqwY2xiayT3Azk0O66R
            EfIJZ1cGBEaLNw0dqoC3s3D9lyWJL4cD4K58AF6KDP1Xe99A1bUakHu8/jQ1MJ/r
            ZUQL5IdRSjcJsC5qxvxzlZ0kCKinVvo+V0kaclrQNlu768qoHZWoxm9zaNsqZhLE
            kFN7sBOjWMJnBeywIPEOz9vzuarMYscKuIQojK1ylUUzCJG3ynalSq/GVpalUHqb
            eEvEc1g76gLrq5GnRXpWsapvfqne74oPJ+3no+GGTZVQxZRM0yuXAfQXohVLqYD2
            gJqD1+xI7p0FX5u+OzvardP6//YIlSq8ppCsU/K0BhYMbOD3PvUO6vQ4EZxetwHT
            Wr0MuRPe/SKNlHaYtZan6cP9nPvbrqvI8FGxsFioCnec+t2MoqbLwxKRjCYpanbD
            K5yszSLwVgADqz8pP2cP4eEWvZDkxJdA4i3wwx7uKi5+VjIaoEpNyO5bEq5iNsIn
            rxep43bF5qthB9ilc/a638lG7GyuIjwz2mUpsLw9tO1QGgTR+MPzcs5ZpEaMe0Ej
            8pa3atsq5j4rFejZSR9+JRCOdEhkEx+PwEfSZOtLtFsc3HzqTQgr8GAgiK5+NVTH
            pdY2lzJZvlK+9DmHqXcthTUkLFujKiI6j8xgh8ItFmrdi+yLWg05LzHADp2JgYHS
            XgGUsJtsqZi5cJogL/ox60hBEU/HZArc80Em9wXlM0pN4qGjj7JHkkmKZMpGs9/4
            fy+eDWt16rYVkaRKRc5UHPX+jS4vT0L1oml+dvhnn+5EaATSAqyKL/VODEyxZJQ=
            =N8/8
            -----END PGP MESSAGE-----
        fp: 4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
