---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: parse-solver-inputs
spec:
  templates:
    - name: parse-solver-inputs
      resubmitPendingPods: true
      inputs:
        parameters:
          - name: "THOTH_DOCUMENT_ID"
          - name: "THOTH_SOLVER_NAME"
          - name: "THOTH_SOLVER_PACKAGES"
          - name: "THOTH_SOLVER_INDEXES"
        artifacts:
          - name: "outputdocument"
            path: "/mnt/component/document/{{inputs.parameters.THOTH_DOCUMENT_ID}}"
      outputs:
        artifacts:
          - name: solvermessagesdocument
            path: "/mnt/workdir/solved_messages.json"
      container:
        name: parse-solver-inputs
        image: workflow-helpers
        env:
          - name: THOTH_WORKFLOW_TASK
            value: "parse_solver_inputs"
          - name: "THOTH_MESSAGING_COMPONENT_NAME"
            value: "solver"
          - name: "THOTH_SOLVER_DOCUMENT_PATH"
            value: "/mnt/component/document/{{inputs.parameters.THOTH_DOCUMENT_ID}}"
          - name: THOTH_SOLVER_NAME
            value: "{{inputs.parameters.THOTH_SOLVER_NAME}}"
          - name: THOTH_SOLVER_PACKAGES
            value: "{{inputs.parameters.THOTH_SOLVER_PACKAGES}}"
          - name: THOTH_SOLVER_INDEXES
            value: "{{inputs.parameters.THOTH_SOLVER_INDEXES}}"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workdir
