apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imagestream.yaml
  - argo-workflows/sync-template.yaml
  - openshift-templates/syncJob-template.yaml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app: thoth
  component: solver
