---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: graph-metrics-exporter-cf
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: null
  workflowSpec:
    entrypoint: graph-metrics-exporter-cf
    serviceAccountName: argo
    templates:
      - name: graph-metrics-exporter-cf
        archiveLocation:
          archiveLogs: true
        dag:
          tasks:
            - name: graph-corruption-check
              templateRef:
                name: graph-metrics-exporter
                template: graph-metrics-exporter
              arguments:
                parameters:
                  - name: "THOTH_GRAPH_METRICS_EXPORTER_TASK"
                    value: "graph_corruption_check"
