---
kind: ConfigMap
apiVersion: v1
metadata:
  name: slo-reporter-stage-prod
data:
  thanos-endpoint: "http://prometheus-portal-thoth-infra-prod.apps.zero.massopen.cloud"   # TODO: Use Thanos endpoint when available and set correct secret
  smtp-server: "smtp.corp.redhat.com"
  sender-address: "aicoe-thoth@redhat.com"
  email-recipients: "aicoe@redhat.com"
  deployment-name: cnv-prod
  amun-inspection-namespace: thoth-amun-inspection-prod
  amun-namespace: thoth-amun-api-prod
  backend-namespace: thoth-backend-prod
  middletier-namespace: thoth-middletier-prod
  frontend-namespace: thoth-frontend-prod
  infra-namespace: thoth-infra-prod
  storage-bucket-name: cnv-prod
  bucket-name: "thoth"
  bucket-prefix: "data"
  public-bucket-name: DH-PLAYPEN
  host: "https://s3.upshift.redhat.com/"
  endpoint: "https://s3.upshift.redhat.com/"
  host-url: "http://prometheus-portal-thoth-infra-prod.apps.zero.massopen.cloud"
  user-api-url: "user-api-thoth-frontend-prod.apps.zero.massopen.cloud:80"
  instance-metrics-exporter-infra: "metrics-exporter-thoth-infra-prod.apps.zero.massopen.cloud:80"
  instance-metrics-management-api: "management-api-thoth-frontend-prod.apps.zero.massopen.cloud:80"
  pushgateway-host: pushgateway-thoth-infra-prod.apps.zero.massopen.cloud
  pushgateway-port: "80"
  pushgateway-url: pushgateway-thoth-infra-prod.apps.zero.massopen.cloud:80
  instance-workflow-controller-metrics-backend: "workflow-controller-metrics-thoth-backend-prod.apps.zero.massopen.cloud:80"
  instance-workflow-controller-metrics-middletier: "workflow-controller-metrics-thoth-middletier-prod.apps.zero.massopen.cloud:80"
  instance-workflow-controller-metrics-amun-inspection: "workflow-controller-metrics-thoth-amun-inspection-prod.apps.zero.massopen.cloud:80"
