apiVersion: v1
items:
-   apiVersion: v1
    data:
        key-id: ENC[AES256_GCM,data:J4ihYCC4CazQ2I6Vw+gkXoy4MwukUFnMJfSrVw==,iv:e6pLqdW9uFQzpR/9WrxG7ma/g8afedLJdja6Y1yu8yc=,tag:MT6E2Uccfy6gX1BLbjrMsA==,type:str]
        secret-key: ENC[AES256_GCM,data:4D+J6Wn6VmJnWpRIfjzpFczWdUYtQe626y6puOQqwhG0/UjNV5L/3gw6wXW5TK082E7NpImj8hM=,iv:mjI0dbf0WHCMxPCG//9CEqAOpXWQtRUqC6G3KS8Npf4=,tag:cu4Nn7R7gNeEK67nzDIzXg==,type:str]
        token: ""
    kind: Secret
    metadata:
        name: slo-reporter-stage-prod
    type: Opaque
kind: List
metadata:
    resourceVersion: ""
    selfLink: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-01-13T17:08:59Z'
    mac: ENC[AES256_GCM,data:MAbwX/Xt7qKTJZJAarHPmjonVmz9LgOCn+q5R3fh1oebCWm0f0l12m5ETnT8zZeKqsjEWUGN+3XPZe9pyHPL1Wsmit/sWJWxo2CwP+csaiWISRPZnNPp9nezARaUvYAF3FjnwFRNygVAERDNwGMDya09b1wakadAPOWOjU64GPA=,iv:M+hRNTuiLUMBhtDYMtqypjk5Cng5BX+AaUI8/AsXSFA=,tag:wDzw5XMfcvRxlz3JvYq2lg==,type:str]
    pgp:
    -   created_at: '2021-01-13T17:08:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYAQ//QnAJGJ9AWkaWQQprg+w/T9J/ba8FLRdZe7rd42CNrzgS
            G3usQsgn642pU/RuwVSDgEI6lbBr4qsPFDqpcNWclrrs+2IBMJMuKlm/yXzdhIZ4
            4a2ymMoCSbqJZSm9pi59P3M0lgrOW++WpS1EIjYoNja8YH3NPzj50AQJfZfnPmxo
            5ejBHjKs8XOYHsJOYJ6HOi/7Z66MXAb4L2wRsxhU09jWFA6VO2XClbb1M9emBsPn
            BUrQF732o5lJhAu2Ma1FLjc4xih7ZEAZZsDpnNBlJRrqKRA49dEzzvb2JnawdhpL
            IO0wsLoyM2buVImwRTqNyXNz5fBSuv+1grLNbML6Fc/ve2zwDtcR9lEJ5dbUz2E0
            DC2GVLKqW3eokRUiEmPW6w0q56ydO2LKMQlrjXGkKqHG2g4BG9ATqeLpbiY8IwG3
            +asUekIuYdXSmZ1KljWgEorZ8cLYNosi+dIIVpZMsREo/GJMEK48lPdJH5CNR6kF
            jkZVuCQ96iGFmWQDAq7e15MeYe3UKf6D1JcgkSSUtiOPOXZQYIV68IngOdfWym5n
            sAHMSk2+ZIpWqz4iGRa+zvUp1r11jNMj2qaz5iYqjIGw8Fwz3dIuxFc0XLp0rCfh
            XhG7cjHkuO/nutbe9Mr6m6w+mIVMYRaajc/FwIXaCTGktaeKMcX/3YJf5Ox182HS
            XgHuFPpGQGVkwrHDmS3ednZFUeZy0yQSGY2vhYL6uFQqPCpZ+soszOrxrVi9h8LE
            s1wy2INUF9NdL0O0DkM+8/GU2yq0laWChs8BiI1rydl7FMsv8Vqk/UAPkXSE0mU=
            =JJ/Z
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-01-13T17:08:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf9Ei/ww5/Z1WxtVYmsIQhPTBBtj1fTdXLHIcO1rsyR5X+P
            abfgdPCpSDRLPQA6R1zBA5H6wKzfzgIy+/vFFkhR73WjZvdTfUQzduEJPLeHrhxB
            3aoAxHfPR54+TBIirT2SQ5uWUa/5SmUUZTmEoNX662CPolktD35BnAbcQfQbChfN
            UcbnlSOLp372EekrEcmxNDt+J0PV7D84RkJCrK/sKnDIknGliZ/Nngl7D6pTeDwm
            vI4Yr0KqdSzj8g6tiWcJWGy0B2y1K2JFKT5PnE1V0GUkvyWWE4/6igorL34Bon8W
            AY3o2eX84iv8d87PebBF+LyqhumNXmQK0N7pgslJadJeAQEEPqQJsuAbm1lg+FXI
            qXjMr8xFhCgID5HtBcozRFW/tGzZkUSAHgCyo5GqCayH3ZuTU2mcwwakiP8Dymoa
            IFfW8zfN7ZVHXDN5rWkptsQaVJAurOKPDIsb7k61sQ==
            =CLlf
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-01-13T17:08:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/ULl+RTbhtCzHa6Pk8NaCXzXFxZme2Uk/FFeO4woFS+qO
            3AAxWLFZZPvndgbv2mJxwmonr63Ra7tpF2NAZjW9LGhJ+3BuXk1zirQten5a2dyv
            a26okQefqkU+0QC/FYzt7PUU+GC3ZKqpPfDE/gLIDNUy+A+YfPDEItoPsIfNmhQn
            C4/x77JxNFAzz2AMp2mDoAoKaE/RVuUV1VvchtldyJeoErf1jSCk8dED0/Yoh/+y
            taNrU3ALLqKZXTPrbpa7pkqe+Br3o6LPLjErHRwcp+gDfs7KVxUEasf62BOCfom5
            wSRHNMZFZLB+NN/yXuM/QZO++rrb3c6Ym1OIiDtbDNJeAQrrygXHfO5CLt0kdHBH
            XmJF7nrA5UPtgQyNT4CCV9q2AllwbF2n8jrK/IL4tfmdarYdGF3sTndyxGPdg9LW
            36PH4OvmlrgSmhG49jpqLK12F9mtauBOEiZmya1TlQ==
            =0YIx
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-01-13T17:08:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7vMDF1jUn3mARAAsS+9jvH4QfztEprx6Bt5N8c3pGOj3WdWhr3eE8d487mm
            DPTxjYG3hMeUGn9ohxBrSoJVbDVAkYGBL5VbNb5PMMOwuJ1j8s1RXm6QdqC3MT2G
            5KzCt874mAiF5BTzOhagcM5i+RowPOdV4dOOnmA2yQeDCUwRC9fPsKYU0uvM05s+
            t7oFj9iAQlIW2ZCZWBoqjRXq2g7PcOO3ol5QBpaeKZhrfrqNfCkZPmbs5GK1iUVB
            t6aRmipxHFamynQZ+d7H2RBLY3z560STgzs2sQzFLYn/lOvOpWDzlzrtDsZd1jdI
            uU5zY3Orz2CBwsjAhLUTavuHSQSXOj8sVTOtIXYAzO3Gc832TEFKiGB1UnUY9eZw
            3rM45meD3EbrSKgvBYPswdSarlX4a4cEuhOOJLeHtRK5ATIuHbJdFw2j+GXEOEuR
            6sl6gf2wQI2tNlGgar1zMvqAY4X1FIrKp0/53vXCVXDp+oF9315zQ8f4rmaCnl7G
            nBLj5n8inlsbV9D7tbmmRHYOPY/er3XAHqNak4ifCFZ74+GzHFDpnYrN/Lil/5r9
            bM60uUugRQeX+yaNnu9/HuqHZP2sMKcUrKWWxUmVsYyTGI9y+QJWc2UF+7elUvbs
            dIc5vybKzwlpm57UprlsGX1GIqsrSqOyIedMDaWTK1WKS+dmoh6Qtb24sTzP2IjS
            XgFHfLVXz7+DoZmA9xcPMd9wlxyjmugW32RY6YMNVe54yJMK6lAS4acdT9FPRuU5
            ypeW2pBPn/2Z7k0bRo0lfQkqMMUK9BnX5yDEqbQVO4j2/gwg6CintlRsnVt1LNQ=
            =dr77
            -----END PGP MESSAGE-----
        fp: 68BD1529A372C8BA561C9DDC377298152D08B95B
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
