apiVersion: v1
items:
-   apiVersion: v1
    data:
        key-id: ENC[AES256_GCM,data:j2S26QvBvu/UkXX0iPjIOuxY7716jHQxYuuVGQ==,iv:RMjYKg5LBAdVqm6/vGT+zcMq4RL8uqw6d173tkB7rWU=,tag:4W7G1mfU//RVDgFGxZRZ0w==,type:str]
        secret-key: ENC[AES256_GCM,data:v4BptYgZDkgjjqNZiJz+6imFDv3xU542fLqzUIT3oDz4NEQAZsLWyAxm5I6T8RMf3751LSm6Q/s=,iv:7Ee9yeIUo899w1rUOoz0bAo+mtGfiQeQ60W+1ye72ck=,tag:VG2gdVvFj3XwRy6Qg6j0AA==,type:str]
        token: ""
    kind: Secret
    metadata:
        name: slo-reporter-stage-prod
    type: Opaque
kind: List
metadata:
    resourceVersion: ""
    selfLink: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-02-16T19:13:27Z'
    mac: ENC[AES256_GCM,data:5Pyfi8TwO4NN/T6G5xLIxOBzZNWW2QVuhnOrJutR9+pk7LKPOaLx0C0CUxXe2Z64STD16kcrE+yABLgVCuGY+dOVM7XbzElZ0e2mh0uUslpBAeMGOO/OeAVy/dGoc4IG0HUZJoX2EcoGXQiiwrxJGqn8949YXBYUxzbVo30ymY8=,iv:z2ovdFiZdiQc3udaWZ7Qr6rRT7Z5MzIjD1lWa7YpOvM=,tag:zzHV8svcyS/snwBXwx5fTQ==,type:str]
    pgp:
    -   created_at: '2021-02-16T19:13:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYAQ/8DOvAd3uL5e1D6/QYF8WJIlLtOmu1dmdV/ToCJKMWDL0a
            DFmgMU/xMqu/iRF3CR/zRvxU1HdcokaMbpRSflI1XsoP0AVO3gSe5lXRhvrFMPxZ
            A8tW1tZWvdAfoV1A1XZpLC0Evu1M6FtOeW/OGk3u0fZb3JHdJPkKR3ph67AS481Q
            g3tyLxzDJrWp6kd2Y0yVHKvhqK9FQuYqC/DzrPpU798y2IaPNBkC7Mya36FKEKtO
            PtY/maIO/kuDTLi11GpV9GMbUD0o25JjKtiHjJhmgjW5HkkJIND0wuSuzSgfUhQs
            lF3M1rFs+8UaUZTYinnwjrr/OMRQQX2qWd6hmlXLHy699nO1ws03Hw68UIxbIeLH
            6za3ysKCw/PMp6iirCGSGVEwxHIlNz16wYA4l14FsyEmRKWzvuQsqRcSvHQujX3n
            cNTRrfXmvibRvT+Fg3fE8gRSeqGmUwYuPVBHsaJVhnAJKJq6ZpMHXf5F3QHTwxPe
            ExE5h7nm+RuSIj5W3ZoCpZ2tVaQwEWBGFR9f0OulNnmt/zMyXoD07EPMW7WsD9bT
            mpLg0crF8bK6nmxhMv0Uh6hbuloumtramW73pl61KgwFXkx7ZoRM95XwZjpXpv3y
            8POJKKlLaruphYKpNihEgHPShiPVvp4uhMfcalXfSBC4ArLQyohG8pH+5cPizsrS
            XgEdj0YS/1UWI6SLaS60Rk/hr1fOcPCjguLmmSHW0jyL/FlCvq5T8L3tHa4YgUOv
            Jkj8APRCTDO3YceIvDKDecfSMzwhVy5ryQQiI3YqTjT4BbS0bJzctugywSlQYys=
            =wgkK
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-02-16T19:13:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf+IXP2eBioFxgtk9qJV3upixxAENA0CIx4GDw0f9wGqvZv
            f9hMNzog4zKf3rfBK9Kg+V+NFI1b4mQzrxg904GZahBcB9otN7kztACglGAXT4or
            VfcDd8ZKY/hQ91P/eMKdHBwkhJu8F0JuR08ChP6aKsqRcGCGQy4GhuVEaGdLDHdg
            jbJ487X7TkabpuHYCWYgQl9KpL3QkWq/5Gc5h2hTidmtAXqOLp+JPp4b+BzdPfIt
            yyC4urnRchgO9xyooRzbSWIcqYo4fe6xRwlADaG409oiYbvL/Z1Jmp7xop7z7FMK
            XdiJAWJXzwmhVGk8Pn0CR4GAESl8Dxas4Bgd1Mpc1tJeAc7V+j8rEwgHmDDKA5vx
            Eo6N2UZ9+pOanGdcSekqA2Zqf36/9Z4Ga/PXB0zYkahSjbKvuu5ND9up5YYJVZh4
            /34z54+LecXPaCDUfODRGGRcm5tc1pfnskMnbYbAsA==
            =CoD3
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-02-16T19:13:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAm+fL+UhEapkxVbnWdTt4IBYbuN38ovxevwchxHpvQ10D
            94BJx3a7HzycHzV4fSDsRGpPd9BV2iHYEtK7gspf2IT0s1dzJfLvfD+5ArrkpKr8
            YC8VBGr2RIrpLdiJViMvSPxVEbeUy2wgjOUdHR7tnLiNimdNLoVuKeiCV2KKTkfc
            RoYnodWQ49RfP9wkKb6MaIeu+ToDT8IQwWhGCxF3w8VUT/JR6Gwrho9SNWp3+k0L
            428sirhHa/y41SMc3jmXa3UxSuA1n/dUeEiLaaFMFooENkCMSJSRsoq4n7pjfmqD
            jKPw7vnLFGY0EC9PkA5xYAXM5ouMTX3sF34mrbYN7NJeAZ3EJ1Lv64uLDZTuAgmA
            kXVUf3XvUXpDhbS5Doan2ErO+z6lZQIkAdk+iez29B/UxP/UVpuqnpTbPIbUSTjb
            1QK3FG1IIOq/3l/Bzrjv973w7zUkxgArv4hFVnvbGg==
            =HYGo
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-02-16T19:13:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7vMDF1jUn3mAQ//cUzrX5XaPjbpXq9Qrb+k4OGhQ1yiA7iWdBQvKH/feUfa
            FKPFXA0Wk3j8aFsCeHxIdlSFbSafUMQJGbTDAZ/2YFWNgNrfb3EC4ZXE4BzjXpeX
            fmM5lMHJuqAoYUiuNw+/XOuhdCH5EU6mWW0qns5SaXYzqa523j7+HZvFXngXvMwp
            Nlru2WEGTHW2T5g7zIreMvRZKXvg1cZ1j7eQAWKaE10XaimdZ2T8hZaVV21CXpaO
            ahAbME0YCWBlb3EBxMgg+XsBbRdewMuO0AzpG5zjzwNnTbedUOC5fIY8sd4b9tTq
            CLfjED/IZO7GDxQlMcQ3jnu1WxUqED2som8WpgFb+ZLKj1IcObr+PsHvI1nFG3LU
            WvBXgJU+kY8h2CmaKaabErLx+8W9xRp8w/CFaN5VvrfTR+U7wuL+RkQoNGkLWTwY
            ZFi1O9KsIjFPtswjrxbX1yv5tyBOoil03RFEezQbo5BLDy00T1oS0ovOGaSwwPyc
            31+5qHm7g0JC2r8g7XzqKTgD3SqwA11QFhNd6LR44WeVllZz1xCfZg+6ZziFy93M
            K41Ay7yD8g/FVFeoIlkXp71//dp8siCV5YCbLzp/OweE4lN/YOhaQlm8d2e8+qwJ
            S6GBnp9kC4JMQya0WP+wG0LMNlU9ZGP+rQW1CLgYkyeT97Jrnv3DM89gKLkiJFjS
            XgGBrS1LpRfb1FTg5e1JKrHim7dQUlEgNsGgNoBkqb4K28nM5y7edARWd2mc4BLB
            HAcecUZv9+iYEmubgd7xveF7c8e4XuB90SOkWYUXzb1rsd7PaMilMMba3WCcFYQ=
            =aaYK
            -----END PGP MESSAGE-----
        fp: 68BD1529A372C8BA561C9DDC377298152D08B95B
    -   created_at: '2021-02-16T19:13:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiARAAu7TsNUdW4X0cmmMrbNT2YzXbdNyfcZQOHzBAPI3u8Cfj
            DXIvAzknw6Y9LtZbeR0p4c4DlfN6OmHmdackX/4nyGE+Ow7uByPi1NM/EdisZjtt
            NAk6I3eNA4cIgGmELGy/Wj2M34qhVay5Tt/ze1WRE2teOo4FopiHaYzZJYnCBiph
            h7f+k8qWrkm/MiYsMx+zMcJwK256rOek/VlG6j6N9FAu/hWj4snhvj/69fYIWTY/
            veAxZklihYVO/tYtBe+cZ5RsvFBSa1hld2ioI3c1KyvRudoECOUs3w0L7vzxkHTN
            rYnwcySE41549D3yZcie7VrIIr8odb25tJWaFfXSMnlPMQdTXsVSK22HOpAHn6ni
            w/t4EwS8N06zElIKu5ruV+rdvrYjVKa/47un/EaqmnZGRDKjQEpDDO+UwObONrJw
            hLxiF1vDScZR+STzGjK6qCCRvz34h5Xfe0AxuqR8MH7otPeNDbTrB6AFaQJ/z+F5
            urfcLSRKRXxr5Djzm0WkrrgQytFtF/iggC/rMWhYV02IQdh7yd1e+9fc4eBAXh8J
            qUOE+GgxRQYNI74kUMbjVOV57CHQmcE61l5tenbP1BABAmYsV/BHY91pNed9PM0D
            UqpsEaSIyPI39SbEr0+PRSYxF6Q4TRBzIIYLbQUThklBEJXZXCFsEdl3cUbWxiTS
            XgEvkCbboXcsTLncRy0aMw4DzqQkcj5yklZexjFSRg/Aus1jXXEdQgd93NoF3ZQv
            wYXECn/fwfyt/TpwHx1kNeDH1JresQdwyn56oJMwkltrIaz837uuhJmEKQL/ps8=
            =5AL2
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
