apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: download-package
  labels:
    app: thoth
    component: download-package
spec:
  templates:
    - name: download-package
      resubmitPendingPods: true
      inputs:
        parameters:
          - name: THOTH_PACKAGE_NAME
          - name: THOTH_PACKAGE_VERSION
          - name: THOTH_PACKAGE_INDEX
      outputs:
        artifacts:
          - name: messagestobesentdocument
            path: "/mnt/workdir/message"
        parameters:
          - name: failed_status
            valueFrom:
              path: /mnt/workdir/failed_status
      container:
        name: download-package
        image: workflow-helpers:test
        env:
          - name: THOTH_WORKFLOW_TASK
            value: download_package
          - name: APP_SCRIPT
            value: app.sh
          - name: THOTH_PACKAGE_NAME
            value: "{{inputs.parameters.THOTH_PACKAGE_NAME}}"
          - name: THOTH_PACKAGE_VERSION
            value: "{{inputs.parameters.THOTH_PACKAGE_VERSION}}"
          - name: THOTH_PACKAGE_INDEX
            value: "{{inputs.parameters.THOTH_PACKAGE_INDEX}}"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - mountPath: /mnt/workdir
            name: workdir
