apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: graph-update-schema
  app.kubernetes.io/managed-by: aicoe-thoth-devops
generatorOptions:
  disableNameSuffixHash: true
resources:
  - imagestream.yaml
  - openshift-templates/schemaUpdateJob-template.yaml
